/**
 * timeline_data.js
 * Statische Geometrie-, Epochen- und Entitaetendaten fuer den Vektor-Zeitstrahl
 */
window.TimelineData = (function() {
    const X = {
        1844: 50,
        1853: 125,
        1892: 235,
        1921: 345,
        1937: 420,
        1944: 455,
        1946: 470,
        1953: 525,
        1963: 600,
        1974: 675,
        1979: 715,
        1986: 775,
        1993: 835,
        1996: 870,
        2000: 905,
        2001: 920,
        2006: 975,
        2011: 1030,
        2016: 1085,
        2021: 1140,
        2022: 1155,
        2031: 1250,
        2044: 1350,
        goldenStart: 1365,
        goldenEnd: 1455
    };

    const ENTITIES = {
        'cycle': {
            id: 'cycle',
            nameDe: "Bahá'í-Zyklus",
            nameEn: "Bahá’í Cycle",
            subDe: "Vorgesehen für mindestens 500.000 Jahre",
            subEn: "Destined to last for 500,000 years",
            categoryDe: "Universaler Zyklus",
            categoryEn: "Universal Cycle",
            periodDe: "500.000 Jahre",
            periodEn: "500,000 years",
            startYear: 1844,
            endYear: 501844,
            color: "#1B2A58",
            descDe: "Der universale Zyklus der Erfüllung der gesamten Religionsgeschichte der Menschheit. Er umfasst zahllose zukünftige Offenbarungen unter dem Schatten der Offenbarung Bahá'u'lláhs.",
            descEn: "The universal cycle fulfilling humanity's religious history, destined to unfold over hundreds of thousands of years under the shadow of Bahá'u'lláh's Revelation.",
            quote: "„Dieser gewaltige Zyklus, der die Sendungen aller vergangenen Propheten krönt und vollendet, ist für eine Dauer von einer halben Million Jahren bestimmt.“",
            quoteSource: "Shoghi Effendi, Die Weltordnung Bahá'u'lláhs"
        },
        'era_c1': {
            id: 'era_c1',
            nameDe: "1. Jahrhundert der Bahá'í-Ära",
            nameEn: "1st Century of the Bahá’í Era",
            subDe: "1844–1944 (Sendung des Báb & Bahá'u'lláhs, Wirken 'Abdu'l-Bahás)",
            subEn: "1844–1944 (Ministry of the Báb, Bahá'u'lláh & 'Abdu'l-Bahá)",
            categoryDe: "Bahá'í-Ära",
            categoryEn: "Bahá’í Era",
            periodDe: "1844–1944",
            periodEn: "1844–1944",
            startYear: 1844,
            endYear: 1944,
            color: "#1F6FA8",
            descDe: "Das erste Jahrhundert der neuen Ära umfasste die heroische Anfangsphase des Glaubens, das Märtyrertum des Báb, das weltweite Exil und die Schriften Bahá'u'lláhs, die weltweite Reise 'Abdu'l-Bahás sowie den Beginn des Baus der Administrativen Ordnung unter Shoghi Effendi.",
            descEn: "The first century witnessed the Heroic Age, the martyrdom of the Báb, the revelation of Bahá'u'lláh, the ministry of 'Abdu'l-Bahá, and the establishment of the Administrative Order under Shoghi Effendi.",
            quote: "„Ein Jahrhundert voll unaussprechlicher Prüfungen, heroischer Taten und unvergleichlicher geistiger Triumphe ging zu Ende.“",
            quoteSource: "Shoghi Effendi, Gott geht vorüber"
        },
        'era_c2': {
            id: 'era_c2',
            nameDe: "2. Jahrhundert der Bahá'í-Ära",
            nameEn: "2nd Century of the Bahá’í Era",
            subDe: "1944–2044 (Weltweite Ausbreitung & Reifung der Gemeinde)",
            subEn: "1944–2044 (Global Expansion & Maturity)",
            categoryDe: "Bahá'í-Ära",
            categoryEn: "Bahá’í Era",
            periodDe: "1944–2044",
            periodEn: "1944–2044",
            startYear: 1944,
            endYear: 2044,
            color: "#1F6FA8",
            descDe: "Das gegenwärtige Jahrhundert der Bahá'í-Ära ist geprägt von der weltweiten Verbreitung des Glaubens auf alle Kontinente, der Errichtung des Universalen Hauses der Gerechtigkeit (1963), der Entfaltung des Trainingsinstituts und der Freisetzung der gesellschaftsbildenden Kraft der Lehren.",
            descEn: "The current century marks the global consolidation, election of the Universal House of Justice (1963), institute process, and release of society-building powers.",
            quote: "„Das zweite Jahrhundert der Bahá'í-Ära ist die Arena, in der die Verheißungen der Zwillingsmanifestationen ihre weltumspannende Reife erlangen.“",
            quoteSource: "Universales Haus der Gerechtigkeit"
        },
        'dispensation': {
            id: 'dispensation',
            nameDe: "Dispensation Bahá'u'lláhs",
            nameEn: "Dispensation of Bahá’u’lláh",
            subDe: "Vorgesehen für mindestens 1000 Jahre (ab 1853)",
            subEn: "Destined to last at least 1000 years (from 1853)",
            categoryDe: "Göttliche Offenbarung",
            categoryEn: "Divine Revelation",
            periodDe: "mindestens 1000 Jahre",
            periodEn: "at least 1000 years",
            startYear: 1853,
            endYear: 2853,
            color: "#00A3E0",
            descDe: "Die göttliche Sendung Bahá'u'lláhs, die im Síyáh-Chál zu Teheran im Herbst 1853 ihren Ursprung nahm. Ihre Gesetze, Grundsätze und Institutionen leiten die Menschheit in das Zeitalter des Weltfriedens und der weltweiten Einheit.",
            descEn: "The Dispensation of Bahá'u'lláh, born in the Síyáh-Chál of Tehran in 1853, ordained to last no less than a full thousand years to guide humanity into global peace.",
            quote: "„Die Offenbarung, die von jeher das Ziel und das Versprechen aller Propheten Gottes und die Sehnsucht aller Völker der Erde war, ist nun den Menschen kundgetan worden.“",
            quoteSource: "Bahá'u'lláh, Ährenlese"
        },
        'heroic_age': {
            id: 'heroic_age',
            nameDe: "Heroisches Zeitalter",
            nameEn: "Heroic Age",
            subDe: "1844–1921 (Apostolisches Zeitalter)",
            subEn: "1844–1921 (Apostolic Age)",
            categoryDe: "Zeitalter des Glaubens",
            categoryEn: "Age of the Faith",
            periodDe: "1844–1921",
            periodEn: "1844–1921",
            startYear: 1844,
            endYear: 1921,
            color: "#4A6D32",
            descDe: "Die Urphase des Glaubens, begründet durch das Wirken der drei Zentralgestalten: der Báb (Vorläufer), Bahá'u'lláh (Offenbarer) und 'Abdu'l-Bahá (Mittelpunkt des Bündnisses).",
            descEn: "The foundational Apostolic Age consecrated by the blood of thousands of martyrs and the presence of the three Central Figures.",
            quote: "„Das Heroische, das Apostolische Zeitalter unseres Glaubens, die Zeitspanne Seiner drei Zentralgestalten, hat Sein Fundament auf ewig gelegt.“",
            quoteSource: "Shoghi Effendi"
        },
        'ministry_bab': {
            id: 'ministry_bab',
            nameDe: "Sendung des Báb",
            nameEn: "Ministry of the Báb",
            subDe: "1844–1853 (1. Epoche des Heroischen Zeitalters)",
            subEn: "1844–1853 (1st Epoch of Heroic Age)",
            categoryDe: "Heroisches Zeitalter",
            categoryEn: "Heroic Age",
            periodDe: "1844–1853",
            periodEn: "1844–1853",
            startYear: 1844,
            endYear: 1853,
            color: "#6B8E23",
            descDe: "Von der Erklärung des Báb in Shiraz am 23. Mai 1844 bis zu Seinem Märtyrertum in Tabriz (1850) und dem Wirken Seiner Gefährten. Er bereitete die Menschheit auf das Kommen Bahá'u'lláhs vor.",
            descEn: "From the Declaration in Shiraz on 23 May 1844 to His Martyrdom in Tabriz (1850), preparing the way for the Promised One of all ages.",
            quote: "„O Volk der Erde! Wahrlich, das strahlende Licht Gottes ist unter euch aufgegangen...“",
            quoteSource: "Der Báb, Qayyúmu'l-Asmá'"
        },
        'ministry_bahaullah': {
            id: 'ministry_bahaullah',
            nameDe: "Sendung Bahá'u'lláhs",
            nameEn: "Ministry of Bahá’u’lláh",
            subDe: "1853–1892 (2. Epoche des Heroischen Zeitalters)",
            subEn: "1853–1892 (2nd Epoch of Heroic Age)",
            categoryDe: "Heroisches Zeitalter",
            categoryEn: "Heroic Age",
            periodDe: "1853–1892",
            periodEn: "1853–1892",
            startYear: 1853,
            endYear: 1892,
            color: "#556B2F",
            descDe: "Von den ersten Offenbarungen im Kerker des Síyáh-Chál (1853), über das Exil in Bagdad, Konstantinopel und Adrianopel, bis zur Verkündigung in Akka und Bahjí (Hinscheiden 1892). Entstehung des Kitáb-i-Aqdas und unzähliger Heiliger Schriften.",
            descEn: "From the Síyáh-Chál dungeon to Baghdad, Constantinople, Adrianople, and the Most Great Prison in Akka, bestowing the Kitáb-i-Aqdas and universal peace teachings.",
            quote: "„Die Erde ist nur ein Land, und alle Menschen sind seine Bürger.“",
            quoteSource: "Bahá'u'lláh"
        },
        'ministry_abdulbaha': {
            id: 'ministry_abdulbaha',
            nameDe: "Wirken 'Abdu'l-Bahás",
            nameEn: "Ministry of ‘Abdu’l-Bahá",
            subDe: "1892–1921 (3. Epoche des Heroischen Zeitalters)",
            subEn: "1892–1921 (3rd Epoch of Heroic Age)",
            categoryDe: "Heroisches Zeitalter",
            categoryEn: "Heroic Age",
            periodDe: "1892–1921",
            periodEn: "1892–1921",
            startYear: 1892,
            endYear: 1921,
            color: "#6B8E23",
            descDe: "Der Mittelpunkt des Bündnisses und Ausleger der Schriften. Seine historischen Reisen nach Europa und Amerika machten die Lehren im Westen bekannt; durch Sein Testament rief Er die Administrative Ordnung und das Hütertum ins Leben.",
            descEn: "The Center of the Covenant and perfect Exemplar. His historic journeys to the West and His Will and Testament established the foundation of the Administrative Order.",
            quote: "„Errichtet das Zelt der Einheit; betrachtet einander nicht als Fremde. Ihr seid die Früchte eines Baumes und die Blätter eines Zweiges.“",
            quoteSource: "'Abdu'l-Bahá"
        },
        'formative_age': {
            id: 'formative_age',
            nameDe: "Gestaltendes Zeitalter",
            nameEn: "Formative Age",
            subDe: "1921 bis zur Errichtung des Goldenen Zeitalters",
            subEn: "1921 until the dawn of the Golden Age",
            categoryDe: "Zeitalter des Glaubens",
            categoryEn: "Age of the Faith",
            periodDe: "ab 1921",
            periodEn: "from 1921",
            startYear: 1921,
            endYear: 2044,
            color: "#3B6E32",
            descDe: "Die Periode des weltweiten Aufbaus der Bahá'í-Gemeindeordnung, der weltweiten Verbreitung durch Lehrpläne und der fortschreitenden gesellschaftsbildenden Wirksamkeit.",
            descEn: "The age dedicated to forging and perfecting the administrative machinery of the Faith and executing the Divine Plan.",
            quote: "„Dieses Gestaltende Zeitalter, in dem die Keime der zukünftigen Weltordnung heranreifen, wird durch die Errichtung des Goldenen Zeitalters gekrönt werden.“",
            quoteSource: "Shoghi Effendi"
        },
        'epoch_1': {
            id: 'epoch_1',
            nameDe: "1. Epoche des Gestaltenden Zeitalters",
            nameEn: "1st Epoch of the Formative Age",
            subDe: "1921–1946 (Aufbau der örtlichen und nationalen Räte)",
            subEn: "1921–1946 (Building local & national assemblies)",
            categoryDe: "Epochen des Gestaltenden Zeitalters",
            categoryEn: "Formative Age Epochs",
            periodDe: "1921–1946",
            periodEn: "1921–1946",
            startYear: 1921,
            endYear: 1946,
            color: "#5B8E32",
            descDe: "Shoghi Effendi leitet den weltweiten Aufbau örtlicher und nationaler Institutionen und setzt die ersten nationalen Lehrpläne in Kraft.",
            descEn: "Establishment of the administrative apparatus under Shoghi Effendi, training communities in consultation, elections, and systematic plans."
        },
        'epoch_2': {
            id: 'epoch_2',
            nameDe: "2. Epoche des Gestaltenden Zeitalters",
            nameEn: "2nd Epoch of the Formative Age",
            subDe: "1946–1963 (Zehnjähriger Kreuzzug & weltweite Ausbreitung)",
            subEn: "1946–1963 (Ten Year Crusade & global expansion)",
            categoryDe: "Epochen des Gestaltenden Zeitalters",
            categoryEn: "Formative Age Epochs",
            periodDe: "1946–1963",
            periodEn: "1946–1963",
            startYear: 1946,
            endYear: 1963,
            color: "#5B8E32",
            descDe: "Höhepunkt war der weltumspannende Zehnjährige Kreuzzug (1953–1963), der den Glauben in über 250 Länder und Territorien trug und in der Wahl des Universalen Hauses der Gerechtigkeit mündete.",
            descEn: "Characterized by the Ten Year Crusade, carrying the banner of the Faith across continents and islands, culminated in the election of the Universal House of Justice."
        },
        'epoch_3': {
            id: 'epoch_3',
            nameDe: "3. Epoche des Gestaltenden Zeitalters",
            nameEn: "3rd Epoch of the Formative Age",
            subDe: "1963–1986 (Hervortreten aus der Verborgenheit)",
            subEn: "1963–1986 (Emergence from obscurity)",
            categoryDe: "Epochen des Gestaltenden Zeitalters",
            categoryEn: "Formative Age Epochs",
            periodDe: "1963–1986",
            periodEn: "1963–1986",
            startYear: 1963,
            endYear: 1986,
            color: "#4A7C28",
            descDe: "Erste globale Pläne unter Führung des Hauses (9YP, 5YP, 7YP), weltweites Eintreten für verfolgte Bahá'í im Iran und Veröffentlichung der Friedenserklärung (1985).",
            descEn: "Leadership passed to the Universal House of Justice; early global plans, rise of external affairs, and publication of 'The Promise of World Peace'."
        },
        'epoch_4': {
            id: 'epoch_4',
            nameDe: "4. Epoche des Gestaltenden Zeitalters",
            nameEn: "4th Epoch of the Formative Age",
            subDe: "1986–2001 (Prozess des massenhaften Eintritts)",
            subEn: "1986–2001 (Process of entry by troops)",
            categoryDe: "Epochen des Gestaltenden Zeitalters",
            categoryEn: "Formative Age Epochs",
            periodDe: "1986–2001",
            periodEn: "1986–2001",
            startYear: 1986,
            endYear: 2001,
            color: "#4A7C28",
            descDe: "Vorbereitung auf den Wendepunkt 1996: Einführung der Trainingsinstitute, des Cluster-Konzepts und des systematischen Lernens im Vierjahresplan.",
            descEn: "1996 marked the historic shift to systematic community building through training institutes and cluster milestones."
        },
        'epoch_5': {
            id: 'epoch_5',
            nameDe: "5. Epoche des Gestaltenden Zeitalters",
            nameEn: "5th Epoch of the Formative Age",
            subDe: "2001–2021 (Vier Fünfjahrespläne: Kernaktivitäten & Kulturwandel)",
            subEn: "2001–2021 (Four 5-Year Plans: Core activities & culture shift)",
            categoryDe: "Epochen des Gestaltenden Zeitalters",
            categoryEn: "Formative Age Epochs",
            periodDe: "2001–2021",
            periodEn: "2001–2021",
            startYear: 2001,
            endYear: 2021,
            color: "#3B6E32",
            descDe: "20 Jahre systematischer Kapazitätsaufbau durch die Ruhi-Kurse, Kinderklassen, Vorjugendgruppen und Andachtstreffen in Tausenden von Clustern weltweit.",
            descEn: "Two decades of intensive cluster growth, core activities, and grassroots human resource capacity development worldwide."
        },
        'epoch_6': {
            id: 'epoch_6',
            nameDe: "2. Jahrhundert / 6. Epoche",
            nameEn: "2nd Century / 6th Epoch",
            subDe: "ab 2021 (Beginn 2. Jahrhundert des Gestaltenden Zeitalters)",
            subEn: "from 2021 (Dawn of the 2nd Century of Formative Age)",
            categoryDe: "Epochen des Gestaltenden Zeitalters",
            categoryEn: "Formative Age Epochs",
            periodDe: "ab 2021",
            periodEn: "from 2021",
            startYear: 2021,
            endYear: 2046,
            color: "#2E5D28",
            descDe: "Eingeläutet durch das Gedenken an das Hinscheiden 'Abdu'l-Bahás (1921–2021). Start einer Serie von Plänen bis 2046 zur Freisetzung gesellschaftsverändernder Kräfte.",
            descEn: "The 100th anniversary of the ascension of 'Abdu'l-Bahá marked the threshold of a new series of plans aimed at releasing society-building power."
        },
        'tdp': {
            id: 'tdp',
            nameDe: "Tafeln des Göttlichen Plans",
            nameEn: "Tablets of the Divine Plan",
            subDe: "Verfasst von 'Abdu'l-Bahá (1916–1917), Ausführung ab 1937",
            subEn: "Revealed by ‘Abdu’l-Bahá (1916–1917), launched in 1937",
            categoryDe: "Göttlicher Lehrplan",
            categoryEn: "Divine Plan",
            periodDe: "ab 1937",
            periodEn: "from 1937",
            startYear: 1937,
            endYear: 2044,
            color: "#7A4C1E",
            descDe: "Die Charta zur weltweiten geistigen Eroberung des Planeten. Enthält die Anweisungen 'Abdu'l-Bahás zur Verbreitung der göttlichen Botschaft in alle Regionen der Erde.",
            descEn: "The grand charter for teaching the Cause of God revealed by 'Abdu'l-Bahá during World War I, put into action under Shoghi Effendi."
        },
        'tdp_1': {
            id: 'tdp_1',
            nameDe: "1. Epoche der Tafeln des Göttlichen Plans",
            nameEn: "1st Epoch of the Tablets of the Divine Plan",
            subDe: "1937–1963 (Zwei Siebenjahrespläne & Zehnjähriger Kreuzzug)",
            subEn: "1937–1963 (Two Seven Year Plans & Ten Year Crusade)",
            categoryDe: "Tafeln des Göttlichen Plans",
            categoryEn: "Tablets of the Divine Plan",
            periodDe: "1937–1963",
            periodEn: "1937–1963",
            startYear: 1937,
            endYear: 1963,
            color: "#D48817",
            descDe: "Unter Leitung des Hüters Shoghi Effendi entfaltete sich die erste Epoche des Göttlichen Plans in drei Stufen: den beiden Siebenjahresplänen (1937–1944 und 1946–1953) sowie dem weltumspannenden Zehnjährigen Kreuzzug (1953–1963), der den Glauben auf alle Kontinente trug und in der Wahl des Universalen Hauses der Gerechtigkeit mündete.",
            descEn: "Under the leadership of Shoghi Effendi, the first epoch of the Divine Plan unfolded in three stages: the two Seven Year Plans (1937–1944 and 1946–1953) and the global Ten Year Crusade (1953–1963), culminating in the election of the Universal House of Justice."
        },
        'tdp_2': {
            id: 'tdp_2',
            nameDe: "2. Epoche der Tafeln des Göttlichen Plans",
            nameEn: "2nd Epoch of the Tablets of the Divine Plan",
            subDe: "1963–2021 (Globale Pläne unter Führung des Universalen Hauses der Gerechtigkeit)",
            subEn: "1963–2021 (Global plans under the Universal House of Justice)",
            categoryDe: "Tafeln des Göttlichen Plans",
            categoryEn: "Tablets of the Divine Plan",
            periodDe: "1963–2021",
            periodEn: "1963–2021",
            startYear: 1963,
            endYear: 2021,
            color: "#D48817",
            descDe: "Eingeläutet mit der Wahl des Universalen Hauses der Gerechtigkeit 1963. Umfasste alle weltweiten Lehrpläne des Hauses vom Neunjahresplan (1964–1973) bis zum feierlichen Abschluss des Fünfjahresplans zu Riḍván 2021.",
            descEn: "Inaugurated with the election of the Universal House of Justice in 1963, encompassing all global teaching plans from the Nine Year Plan (1964–1973) to the close of the Five Year Plan at Riḍván 2021."
        },
        'tdp_3': {
            id: 'tdp_3',
            nameDe: "3. Epoche der Tafeln des Göttlichen Plans",
            nameEn: "3rd Epoch of the Tablets of the Divine Plan",
            subDe: "ab 2021 (Schwelle zum 2. Jahrhundert des Gestaltenden Zeitalters)",
            subEn: "from 2021 (Threshold of the 2nd Century of Formative Age)",
            categoryDe: "Tafeln des Göttlichen Plans",
            categoryEn: "Tablets of the Divine Plan",
            periodDe: "ab 2021",
            periodEn: "from 2021",
            startYear: 2021,
            endYear: 2046,
            color: "#B36B00",
            descDe: "Die aktuelle dritte Epoche des Göttlichen Plans, begonnen zu Riḍván 2021 mit dem Einjahresplan und dem aktuellen Neunjahresplan bis 2031 als erstem Schritt einer 25-jährigen Serie bis 2046.",
            descEn: "The current third epoch of the Divine Plan, launched at Riḍván 2021 with the One Year Plan and the current Nine Year Plan through 2031, part of a 25-year series to 2046."
        },
        'golden_age': {
            id: 'golden_age',
            nameDe: "Goldenes Zeitalter",
            nameEn: "Golden Age",
            subDe: "Zukunft der menschlichen Zivilisation",
            subEn: "Future of human civilization",
            categoryDe: "Zeitalter des Glaubens",
            categoryEn: "Age of the Faith",
            periodDe: "Zukunft",
            periodEn: "Future",
            startYear: 2044,
            endYear: 2100,
            color: "#3B6E32",
            descDe: "Die Verwirklichung des Größten Friedens, der geistigen Einigung aller Völker und der Etablierung des Reiches Gottes auf Erden.",
            descEn: "The consummation of the Golden Age of the Cause of God, the Great Peace, and the spiritual unification of humanity."
        },
        'series_prev': {
            id: 'series_prev',
            nameDe: "Vorherige Serie globaler Pläne",
            nameEn: "Previous Series of Global Plans",
            subDe: "1996–2021 (Vierteljahrhundert des Lernens)",
            subEn: "1996–2021 (Quarter century of learning)",
            categoryDe: "Serie globaler Pläne",
            categoryEn: "Series of Global Plans",
            periodDe: "1996–2021",
            periodEn: "1996–2021",
            startYear: 1996,
            endYear: 2021,
            color: "#C5A059",
            descDe: "Eine 25-jährige geschlossene Kette von Plänen (4YP, 12MP, vier 5YPs), die das Trainingsinstitut als weltweites Rückgrat des Wachstums etablierte."
        },
        'series_new': {
            id: 'series_new',
            nameDe: "Neue Serie globaler Pläne",
            nameEn: "New Series of Global Plans",
            subDe: "2021–2046 (25-jährige Epoche bis zur Hundertjahrfeier 2044/2046)",
            subEn: "2021–2046 (25-year series through to the 2nd Century centenary)",
            categoryDe: "Serie globaler Pläne",
            categoryEn: "Series of Global Plans",
            periodDe: "ab 2021",
            periodEn: "from 2021",
            startYear: 2021,
            endYear: 2046,
            color: "#E53935",
            descDe: "Die aktuelle Serie globaler Pläne zur Freisetzung der gesellschaftsbildenden Kraft des Glaubens in Tausenden von fortgeschrittenen Clustern weltweit."
        },

        // DIE LEHRPLÄNE
        'plan_7yp_37': {
            id: 'plan_7yp_37', code: '7YP',
            nameDe: "Erster Siebenjahresplan (1937–1944)",
            nameEn: "First Seven Year Plan (1937–1944)",
            subDe: "1937–1944 (1. Stufe der 1. Epoche des Göttlichen Plans)",
            subEn: "1937–1944 (Stage 1 of the 1st Epoch of Divine Plan)",
            categoryDe: "1. Epoche der Tafeln des Göttlichen Plans",
            categoryEn: "1st Epoch of the Tablets of the Divine Plan",
            periodDe: "1937–1944", periodEn: "1937–1944",
            startYear: 1937, endYear: 1944, startDate: "1937-04-21", endDate: "1944-04-20",
            descDe: "Der erste systematische Lehrplan der Bahá'í-Geschichte, initiiert von Shoghi Effendi für die nordamerikanische Gemeinde zur Ausbreitung nach Lateinamerika.",
            descEn: "Initiated by Shoghi Effendi for the North American community to spread the Faith across Latin America."
        },
        'plan_7yp_46': {
            id: 'plan_7yp_46', code: '7YP',
            nameDe: "Zweiter Siebenjahresplan (1946–1953)",
            nameEn: "Second Seven Year Plan (1946–1953)",
            subDe: "1946–1953 (2. Stufe der 1. Epoche des Göttlichen Plans)",
            subEn: "1946–1953 (Stage 2 of the 1st Epoch of Divine Plan)",
            categoryDe: "1. Epoche der Tafeln des Göttlichen Plans",
            categoryEn: "1st Epoch of the Tablets of the Divine Plan",
            periodDe: "1946–1953", periodEn: "1946–1953",
            startYear: 1946, endYear: 1953, startDate: "1946-04-21", endDate: "1953-04-20",
            descDe: "Wiederaufbau der im Zweiten Weltkrieg verwüsteten europäischen Bahá'í-Gemeinden und Vorbereitung auf den globalen Kreuzzug.",
            descEn: "Rebuilding European communities post-WWII and preparing the global stage for the Ten Year Crusade."
        },
        'plan_10yc_53': {
            id: 'plan_10yc_53', code: '10YC',
            nameDe: "Zehnjähriger Kreuzzug (1953–1963)",
            nameEn: "Ten Year Crusade (1953–1963)",
            subDe: "1953–1963 (3. Stufe der 1. Epoche des Göttlichen Plans)",
            subEn: "1953–1963 (Stage 3 of the 1st Epoch of Divine Plan)",
            categoryDe: "1. Epoche der Tafeln des Göttlichen Plans",
            categoryEn: "1st Epoch of the Tablets of the Divine Plan",
            periodDe: "1953–1963", periodEn: "1953–1963",
            startYear: 1953, endYear: 1963, startDate: "1953-04-21", endDate: "1963-04-20",
            descDe: "Der weltweite Kreuzzug des Hüters Shoghi Effendi als krönender Abschluss der 1. Epoche des Göttlichen Plans. Er trug den Glauben auf alle Kontinente und führte 1963 zur Wahl des Universalen Hauses der Gerechtigkeit.",
            descEn: "Shoghi Effendi's global crusade concluding the 1st Epoch of the Divine Plan, planting the banner of Bahá'u'lláh worldwide and culminating in the election of the Universal House of Justice in 1963."
        },
        'plan_9yp_64': {
            id: 'plan_9yp_64', code: '9YP',
            nameDe: "Neunjahresplan (1964–1973)",
            nameEn: "Nine Year Plan (1964–1973)",
            subDe: "1964–1973 (2. Epoche des Göttlichen Plans)",
            subEn: "1964–1973 (2nd Epoch of the Divine Plan)",
            categoryDe: "2. Epoche der Tafeln des Göttlichen Plans",
            categoryEn: "2nd Epoch of the Tablets of the Divine Plan",
            periodDe: "1964–1973", periodEn: "1964–1973",
            startYear: 1964, endYear: 1973, startDate: "1964-04-21", endDate: "1974-04-20",
            descDe: "Erster globaler Plan der 2. Epoche des Göttlichen Plans unter Führung des Universalen Hauses der Gerechtigkeit. Erhöhung der Nationalen Räte von 56 auf 113.",
            descEn: "First global plan of the 2nd Epoch of the Divine Plan under the Universal House of Justice, doubling the number of National Assemblies."
        },
        'plan_5yp_74': {
            id: 'plan_5yp_74', code: '5YP',
            nameDe: "Fünfjahresplan (1974–1979)",
            nameEn: "Five Year Plan (1974–1979)",
            subDe: "1974–1979 (2. Epoche des Göttlichen Plans)",
            subEn: "1974–1979 (2nd Epoch of the Divine Plan)",
            categoryDe: "2. Epoche der Tafeln des Göttlichen Plans",
            categoryEn: "2nd Epoch of the Tablets of the Divine Plan",
            periodDe: "1974–1979", periodEn: "1974–1979",
            startYear: 1974, endYear: 1979, startDate: "1974-04-21", endDate: "1979-04-20",
            descDe: "Stärkung des Gemeindelebens, Gründung des Internationalen Lehrzentrums (ITC) und Baubeginn des Sitzes des Hauses auf dem Berg Karmel.",
            descEn: "Deepening local life, establishing the International Teaching Centre (ITC), and commencing the Seat of the Universal House of Justice."
        },
        'plan_7yp_79': {
            id: 'plan_7yp_79', code: '7YP',
            nameDe: "Siebenjahresplan (1979–1986)",
            nameEn: "Seven Year Plan (1979–1986)",
            subDe: "1979–1986 (2. Epoche des Göttlichen Plans)",
            subEn: "1979–1986 (2nd Epoch of the Divine Plan)",
            categoryDe: "2. Epoche der Tafeln des Göttlichen Plans",
            categoryEn: "2nd Epoch of the Tablets of the Divine Plan",
            periodDe: "1979–1986", periodEn: "1979–1986",
            startYear: 1979, endYear: 1986, startDate: "1979-04-21", endDate: "1986-04-20",
            descDe: "Hervortreten aus der Verborgenheit angesichts der Verfolgungen im Iran und Veröffentlichung der Friedenserklärung (1985).",
            descEn: "Emergence from obscurity in the crucible of persecution in Iran; release of 'The Promise of World Peace'."
        },
        'plan_6yp_86': {
            id: 'plan_6yp_86', code: '6YP',
            nameDe: "Sechsjahresplan (1986–1992)",
            nameEn: "Six Year Plan (1986–1992)",
            subDe: "1986–1992 (2. Epoche des Göttlichen Plans)",
            subEn: "1986–1992 (2nd Epoch of the Divine Plan)",
            categoryDe: "2. Epoche der Tafeln des Göttlichen Plans",
            categoryEn: "2nd Epoch of the Tablets of the Divine Plan",
            periodDe: "1986–1992", periodEn: "1986–1992",
            startYear: 1986, endYear: 1992, startDate: "1986-04-21", endDate: "1992-04-20",
            descDe: "Voranschreiten des Prozesses des massenhaften Eintritts und Ausbau sozial-ökonomischer Entwicklungsprojekte.",
            descEn: "Accelerating entry by troops and social and economic development initiatives globally."
        },
        'plan_3yp_93': {
            id: 'plan_3yp_93', code: '3YP',
            nameDe: "Dreijahresplan (1993–1996)",
            nameEn: "Three Year Plan (1993–1996)",
            subDe: "1993–1996 (2. Epoche des Göttlichen Plans)",
            subEn: "1993–1996 (2nd Epoch of the Divine Plan)",
            categoryDe: "2. Epoche der Tafeln des Göttlichen Plans",
            categoryEn: "2nd Epoch of the Tablets of the Divine Plan",
            periodDe: "1993–1996", periodEn: "1993–1996",
            startYear: 1993, endYear: 1996, startDate: "1993-04-21", endDate: "1996-04-20",
            descDe: "Reifung der Institutionen und Vorbereitung des weltweiten Netzwerks regionaler Trainingsinstitute.",
            descEn: "Focus on deepening individual and collective life, preparing for the institute process."
        },
        'plan_4yp_96': {
            id: 'plan_4yp_96', code: '4YP',
            nameDe: "Vierjahresplan (1996–2000)",
            nameEn: "Four Year Plan (1996–2000)",
            subDe: "1996–2000 (2. Epoche des Göttlichen Plans)",
            subEn: "1996–2000 (2nd Epoch of the Divine Plan)",
            categoryDe: "2. Epoche der Tafeln des Göttlichen Plans",
            categoryEn: "2nd Epoch of the Tablets of the Divine Plan",
            periodDe: "1996–2000", periodEn: "1996–2000",
            startYear: 1996, endYear: 2000, startDate: "1996-04-21", endDate: "2000-04-20",
            descDe: "Der historische Wendepunkt: Etablierung des Trainingsinstituts als primäres Instrument zur Entfaltung menschlicher Ressourcen.",
            descEn: "A watershed moment establishing training institutes as the engine of systematic growth."
        },
        'plan_12mp_00': {
            id: 'plan_12mp_00', code: '12MP',
            nameDe: "Zwölfmonatsplan (2000–2001)",
            nameEn: "Twelve Month Plan (2000–2001)",
            subDe: "2000–2001 (2. Epoche des Göttlichen Plans)",
            subEn: "2000–2001 (2nd Epoch of the Divine Plan)",
            categoryDe: "2. Epoche der Tafeln des Göttlichen Plans",
            categoryEn: "2nd Epoch of the Tablets of the Divine Plan",
            periodDe: "2000–2001", periodEn: "2000–2001",
            startYear: 2000, endYear: 2001, startDate: "2000-04-21", endDate: "2001-04-20",
            descDe: "Übergangsplan an der Schwelle des neuen Jahrtausends zur Vorbereitung der Serie von Fünfjahresplänen.",
            descEn: "Transition plan bridging into the 21st century and the four Five Year Plans."
        },
        'plan_5yp_01': {
            id: 'plan_5yp_01', code: '5YP',
            nameDe: "Fünfjahresplan I (2001–2006)",
            nameEn: "Five Year Plan I (2001–2006)",
            subDe: "2001–2006 (2. Epoche des Göttlichen Plans)",
            subEn: "2001–2006 (2nd Epoch of the Divine Plan)",
            categoryDe: "2. Epoche der Tafeln des Göttlichen Plans",
            categoryEn: "2nd Epoch of the Tablets of the Divine Plan",
            periodDe: "2001–2006", periodEn: "2001–2006",
            startYear: 2001, endYear: 2006, startDate: "2001-04-21", endDate: "2006-04-20",
            descDe: "Einführung des Cluster-Konzepts und der Kernaktivitäten (Studienkreise, Andachten, Kinderklassen).",
            descEn: "Introduction of clusters and core activities as the standard framework of growth."
        },
        'plan_5yp_06': {
            id: 'plan_5yp_06', code: '5YP',
            nameDe: "Fünfjahresplan II (2006–2011)",
            nameEn: "Five Year Plan II (2006–2011)",
            subDe: "2006–2011 (2. Epoche des Göttlichen Plans)",
            subEn: "2006–2011 (2nd Epoch of the Divine Plan)",
            categoryDe: "2. Epoche der Tafeln des Göttlichen Plans",
            categoryEn: "2nd Epoch of the Tablets of the Divine Plan",
            periodDe: "2006–2011", periodEn: "2006–2011",
            startYear: 2006, endYear: 2011, startDate: "2006-04-21", endDate: "2011-04-20",
            descDe: "Etablierung des Vorjugendprogramms und intensive Programme des Wachstums in hunderten Clustern.",
            descEn: "Emergence of the Junior Youth Spiritual Empowerment Programme and intensive programmes of growth."
        },
        'plan_5yp_11': {
            id: 'plan_5yp_11', code: '5YP',
            nameDe: "Fünfjahresplan III (2011–2016)",
            nameEn: "Five Year Plan III (2011–2016)",
            subDe: "2011–2016 (2. Epoche des Göttlichen Plans)",
            subEn: "2011–2016 (2nd Epoch of the Divine Plan)",
            categoryDe: "2. Epoche der Tafeln des Göttlichen Plans",
            categoryEn: "2nd Epoch of the Tablets of the Divine Plan",
            periodDe: "2011–2016", periodEn: "2011–2016",
            startYear: 2011, endYear: 2016, startDate: "2011-04-21", endDate: "2016-04-20",
            descDe: "Weltweite Jugendkonferenzen 2013 und Entstehung von Zentren intensiver Aktivität in Nachbarschaften.",
            descEn: "Historic 2013 youth conferences and neighborhood-level community building."
        },
        'plan_5yp_16': {
            id: 'plan_5yp_16', code: '5YP',
            nameDe: "Fünfjahresplan IV (2016–2021)",
            nameEn: "Five Year Plan IV (2016–2021)",
            subDe: "2016–2021 (2. Epoche des Göttlichen Plans)",
            subEn: "2016–2021 (2nd Epoch of the Divine Plan)",
            categoryDe: "2. Epoche der Tafeln des Göttlichen Plans",
            categoryEn: "2nd Epoch of the Tablets of the Divine Plan",
            periodDe: "2016–2021", periodEn: "2016–2021",
            startYear: 2016, endYear: 2021, startDate: "2016-04-21", endDate: "2021-04-20",
            descDe: "Zweihundertjahrfeiern der Geburt Bahá'u'lláhs (2017) und des Báb (2019). Über 5.000 Cluster mit Wachstumsprogrammen.",
            descEn: "Twin Bicentenary celebrations of Bahá'u'lláh and the Báb; surpassing 5,000 intensive growth clusters."
        },
        'plan_1yp_21': {
            id: 'plan_1yp_21', code: '1YP',
            nameDe: "Einjahresplan (2021–2022)",
            nameEn: "One Year Plan (2021–2022)",
            subDe: "2021–2022 (3. Epoche des Göttlichen Plans)",
            subEn: "2021–2022 (3rd Epoch of the Divine Plan)",
            categoryDe: "3. Epoche der Tafeln des Göttlichen Plans",
            categoryEn: "3rd Epoch of the Tablets of the Divine Plan",
            periodDe: "2021–2022", periodEn: "2021–2022",
            startYear: 2021, endYear: 2022, startDate: "2021-04-21", endDate: "2022-04-20",
            descDe: "Eröffnung der 3. Epoche des Göttlichen Plans, Hundertjahrfeier des Hinscheidens 'Abdu'l-Bahás und Start in das 2. Jahrhundert des Gestaltenden Zeitalters.",
            descEn: "Opening the 3rd Epoch of the Divine Plan, centenary of the Ascension of 'Abdu'l-Bahá, and inauguration of the 2nd Century of the Formative Age."
        },
        'plan_9yp_22': {
            id: 'plan_9yp_22', code: '9YP',
            nameDe: "Neunjahresplan (2022–2031)",
            nameEn: "Nine Year Plan (2022–2031)",
            subDe: "2022–2031 (3. Epoche des Göttlichen Plans)",
            subEn: "2022–2031 (3rd Epoch of the Divine Plan)",
            categoryDe: "3. Epoche der Tafeln des Göttlichen Plans",
            categoryEn: "3rd Epoch of the Tablets of the Divine Plan",
            periodDe: "2022–2031", periodEn: "2022–2031",
            startYear: 2022, endYear: 2031, startDate: "2022-04-21", endDate: "2031-12-31",
            descDe: "Der aktuelle globale Lehrplan der 3. Epoche des Göttlichen Plans. Erster Plan einer neuen 25-jährigen Serie bis 2046 zur Freisetzung gesellschaftsbildender Kraft.",
            descEn: "The current active global plan in the 3rd Epoch of the Divine Plan, first in a 25-year series through 2046 to release society-building power."
        }
    };

    return { X, ENTITIES };
})();
